rs-station/reciprocalspaceship

reciprocalspaceship/dataset.py, tests/test_dataset.py
I was tired of dipping into `rs.utils` to compute multiplicities, so I made an `rs.DataSet.compute_multiplicity` method. This computes the multiplicity and adds a new `"EPSILON"` column to the data set.
=> new DataSet.compute_multiplicity method

reciprocalspaceship/dtypes/base.py, tests/dtypes/test_dtypes.py
The default behavior for a pandas `IntegerArray.to_numpy()` method is to return a numpy array of type `object`. This ensures support for NaN-values that can be represented in the `IntegerArray`, but not in a numpy array of `np.int32`. 
In order to minimize any surprise that may be caused by this default behavior, this PR changes the default behavior of `MTZIntegerArray.to_numpy()` to be to return a `np.int32` array if there are no NaN values in the array, but to keep the `object` return type if NaNs are present. This seems like a good compromise to maintain pandas-like behavior while improving default numpy conversions in many common cases.
=> MTZIntegerArray.to_numpy() should default to np.int32 where possible

reciprocalspaceship/dataset.py, tests/test_dataset_grid.py
This method is meant to go between the "tabular" view of the data provided by the `DataSet` class and the 3D grid that it represents (values indexed by HKL values).
=> Add DataSet.to_reciprocalgrid() for arranging data on 3D grid by Miller index

reciprocalspaceship/concat.py, reciprocalspaceship/dataset.py, tests/test_dataset.py, tests/test_dataset_index.py, tests/test_dataset_preserve_attributes.py
This PR changes the private attribute `DataSet._cache_index_dtypes` to `DataSet._index_dtypes_cache` to ensure consistent naming for attributes vs methods.
=> Rename private attribute _cache_index_dtypes

reciprocalspaceship/dataset.py, tests/test_dataset_anomalous.py
Fixes #26 and #27.
This PR fixes the handling of centric reflections in `DataSet.stack_anomalous()` and `DataSet.unstack_anomalous()`. After this PR, centric reflections will no longer be mapped to the Friedel-minus ASU by these reshaping operations.
In addition, a `ValueError` will now be raised when `stack_anomalous()` or. `unstack_anomalous()` are invoked on an unmerged DataSet.
=> Handle centric reflections and unmerged data in stack_anomalous() and unstack_anomalous()

reciprocalspaceship/dataset.py, tests/test_dataset_symops.py
Improves handling of centrics in `DataSet.hkl_to_asu(anomalous=True)`. Previously, the `anomalous=True` flag would lead to the remapping of centric reflections to the +/- reciprocal space ASU depending on the observed Miller index. However, it does not make sense to split centric reflections in this manner because they are not valid Friedel pairs. 
This PR fixes the handling of centrics such that they are unchanged by the `anomalous` flag. In all cases, `DataSet.hkl_to_asu()` will map centric reflections to the +ASU.
=> Fix handling of centrics in DataSet.hkl_to_asu(anomalous=True)

docs/api/index.rst, reciprocalspaceship/io/__init__.py, reciprocalspaceship/io/ccp4map.py, tests/io/test_ccp4map.py
This PR adds a function, `rs.io.write_ccp4_map()`, which uses `gemmi` to write a CCP4-format map file from a 3D NumPy array.  This allows one to write map files for real-space density that can be viewed in typical molecular graphics programs (PyMOL, COOT, etc).
=> Add function for writing CCP4 maps from NumPy arrays

docs/api/index.rst, reciprocalspaceship/__init__.py, reciprocalspaceship/io/__init__.py, reciprocalspaceship/io/csv.py, tests/io/test_csv.py
This PR adds `rs.read_csv()` to construct a `DataSet` from a CSV file. This method takes additional parameters that are passed to the `rs.DataSet()` constructor (`spacegroup`, `cell`,  `merged`), and also accepts a boolean `infer_mtz_dtypes` to determine whether MTZ dtypes will be inferred for the data.
Internally, this method calls `pd.read_csv()`, and any additional keyword arguments accepted by the `pandas` function can also be passed to `rs.read_csv()`.
=> Add rs.read_csv() to construct DataSet from CSV file

reciprocalspaceship/dataset.py, reciprocalspaceship/dtypes/base.py, setup.py
This PR updates `reciprocalspaceship` to support the latest `pandas 1.2.0`. Based on testing, this supports versions 1.1.4 to latest, so I have adjusted our `install_requires` in `setup.py` to reflect that.
=> Update to support Pandas 1.2.0

reciprocalspaceship/algorithms/scale_merged_intensities.py, tests/algorithms/test_scale_merged_intensities.py
I updated the French Wilson algorithm so that it wouldn't output NaNs for very small values of I/SigI, and I updated some tolerances in the test. I made them a little bit looser. Now we have to agree within %5 to the table in the paper, and 95% of the reflections must be within 2% of the values from PHENIX. I also got rid of unused posterior functions.
=> will no longer fail for insanely small i/sigma

reciprocalspaceship/dataset.py, tests/test_dataset.py
It is common to need to perform operations separately for centric and acentric reflections. This PR adds new attributes to `DataSet` that act as accessors to centric/acentric reflections. Internally, this operates by calling `DataSet.label_centrics()` and using the boolean mask to access the relevant rows of the reflection table. Centric reflections can be obtained by calling `DataSet.centrics` and acentric reflections can be obtained by calling `DataSet.acentrics`. 
It is worth keeping in mind that if one will be repeatedly accessing these properties, it is worthwhile to cache the results by saving the a `CENTRIC` column. These accessors will use the cached column if it exists instead of repeating the calculation. This can lead to dramatic performance improvements when working with …
=> Add DataSet.centrics and DataSet.acentrics accessors

reciprocalspaceship/io/precognition.py, tests/io/conftest.py, tests/io/test_precognition.py
This PR cleans up `rs.read_precognition()` to better adhere to the style of the rest of `rs`:
- Changes API to accept unit cell parameters as a tuple/list-like of floats
- Changes anomalous columns to use `(+)`-style suffixes rather than `+`
- Minor refactor to use `DataSet.astype()` to set MTZDtypes for the columns
- Refactors tests to use `pytest` functional style rather than the `unittest` style classes
=> Clean up rs.read_precognition()

reciprocalspaceship/__init__.py, reciprocalspaceship/io/__init__.py, reciprocalspaceship/io/crystfel.py, tests/io/test_crystfel.py
This PR adds:
- reading `CrystFEL's` stream files into `DataSet` format without any metadata
- computing columns `ewald_offset`, `s1{x,y,z}` upon reading
- accompanying tests
- example of CrystFEL's stream to test on.
=> Add crystfel streams to `rs/io` module

postBuild, setup.py
This PR updates the "dev" build to include all extra dependencies that are needed to run the example notebooks. The dev build can be done using `pip` and a local clone of the git repo:
```shell
pip install -e .[dev]
```
or using PyPI:
```shell
pip install reciprocalspaceship[dev]
```
The `postBuild` script that is used to initialize the binder environment was also updated to use this set of extra dependencies.
Two benefits of this PR are:
1. Extra dependencies for documentation/examples only need to be updated in one place
2. It is possible to automate the "re-running" of example notebooks at each official release ensure the examples are up-to-date.
=> Add example notebooks' dependencies to dev install

reciprocalspaceship/io/mtz.py
When `rs` runs into trouble converting a column to a `gemmi` compatible `dtype`, it is helpful to know the column name in addition to the offending dtype.
=> clearer error message in `to_gemmi`

reciprocalspaceship/utils/__init__.py, reciprocalspaceship/utils/units.py, tests/utils/test_units.py
This PR will add two new methods to `rs.utils`, `ev2angstroms` and `angstroms2ev`.
=> Adding methods for interconverting wavelength and energy

reciprocalspaceship/dtypes/anomalousdifference.py, reciprocalspaceship/dtypes/base.py, reciprocalspaceship/dtypes/intensity.py, reciprocalspaceship/dtypes/mtzreal.py, reciprocalspaceship/dtypes/phase.py, reciprocalspaceship/dtypes/stddev.py, reciprocalspaceship/dtypes/structurefactor.py, reciprocalspaceship/dtypes/weight.py, tests/dtypes/test_dtypes.py, tests/dtypes/test_floats_pandas.py, tests/utils/test_phases.py
Recently, there appears to have been a change in Pandas that has made our float32-backed dtypes notably slower than native numpy dtypes:
```
In [1] x = rs.DataSeries(np.linspace(0, 1, 1000000), dtype=np.float32)
In [2]: %timeit x / 100
1.97 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
In [3]: x = rs.DataSeries(np.linspace(0, 1, 1000000), dtype="MTZReal")
In [4]: %timeit x / 100
2.89 s ± 186 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
This PR fixes this ~1000-2000x slowdown by reimplementing our float32-backed custom dtypes by subclassing a new Pandas dtype: `pd.Float32Dtype`. This strongly parallels our implementation of int32-backed custom dtypes, and should  allow us to better maintain our code with changes to Pandas internals.
After the change:
``` …
```
=> Change internals for representing float32-backed data

reciprocalspaceship/dataset.py, tests/test_dataset.py, tests/test_dataset_grid.py, tests/test_dataset_symops.py
Based on visual inspection of maps, it appeared that `DataSet.apply_symop()` was applying phase shifts in the opposite direction of the specified symmetry operation. This PR changes the sign for how phase shifts are applied, and updates the relevant test.
=> Fix sign of phase shift in DataSet.apply_symop

reciprocalspaceship/dataset.py, tests/test_dataset_symops.py
Fixes #15 by adding support for complex structure factors to `DataSet.hkl_to_asu()`. This method, as well as `DataSet.hkl_to_observed()` and `DataSet.apply_symop()` now support applying phase shifts complex structure factors as well to `PhaseDtype` columns. 
This method is tested by confirming that:
- `hkl_to_asu()` moves "P1 data" to the reciprocal ASU while correctly shifting the phase for the 63 spacegroups in our fmodel-based test set
- roundtrips of `hkl_to_asu()` and `hkl_to_observed()` preserve the phase of all reflections for the 63 spacegroups in our fmodel-based test set
=> Add complex structure factor support to DataSet.hkl_to_asu()

docs/conf.py, docs/developers/index.rst, docs/developers/utilities.rst, reciprocalspaceship/utils/__init__.py, reciprocalspaceship/utils/rfree.py, reciprocalspaceship/utils/structurefactors.py, setup.py
There are useful functions in `rs.utils` that serve as the foundation for our crystallographic support in this library. These functions could be useful to anyone interested in writing/contributing new methods to incorporate into `rs`, so they should be documented. 
This PR adds a page to the "For Developers" section of the documentation site that describes each of the functions in `rs.utils` based on the relevant docstrings. Only the "public API" of `rs.utils` -- as specified by the `__all__` list in `reciprocalspaceship.utils.__init__.py` -- will appear on the site.
=> Add documentation for rs.utils functions to Developers section

reciprocalspaceship/utils/asu.py, tests/utils/test_asu.py
This PR fixes the behavior of `rs.utils.generate_reciprocal_asu()` with `anomalous=True` to avoid copying centric reflections to the Friedel-minus ASU. This makes the function's handling of centrics consistent with other methods (such as `DataSet.stack_anomalous()`)
I also changed the implementation to use `rs.utils.in_asu()` instead of `rs.utils.hkl_to_asu()`, which speeds up the code ~2x.
=> Fix behavior of rs.utils.generate_reciprocal_asu() with anomalous flag

reciprocalspaceship/utils/phases.py
I made a version of the phase shift calculation that has pretty much everything outside the `for` loop. It is about 3x faster in the test. Hard to say how it would perform with higher resolution data set. This was mostly an exercise to see what would be required to speed this up. I am not going to say whether we should actually merge this or not.
=> mostly vectorized phase restriction calculation

docs/api/index.rst, reciprocalspaceship/__init__.py, reciprocalspaceship/dataset.py, reciprocalspaceship/io/__init__.py, reciprocalspaceship/io/pickle.py, tests/io/test_pickle.py
This PR adds a `read_pickle()` method to the `rs` namespace in order to easily allow roundtrip operations with `DataSet.to_pickle()` and `rs.read_pickle()`.
This method is particularly useful for storing non-MTZ compatible dtypes in a way that can be written to a file for later use in `rs`.
=> Add rs.read_pickle() helper method

reciprocalspaceship/dataset.py, setup.py, tests/algorithms/test_merge.py, tests/algorithms/test_scale_merged_intensities.py, tests/dtypes/conftest.py, tests/dtypes/test_floats_pandas.py, tests/dtypes/test_ints_pandas.py, tests/utils/test_cell.py
This PR updates reciprocalspaceship to support the new release of pandas (v1.3.0):
- Updated to remove numpy deprecation warnings in test suite
- Removed pandas deprecation warnings pertaining to `DataSet.set_index()` and `DataSet.reset_index()` keyword arguments
- Simplified dtype testing by using `pd.array()` to initialize arrays of each dtype
=> Update reciprocalspaceship to support pandas 1.3.0

reciprocalspaceship/io/crystfel.py, tests/io/test_crystfel.py
Modify the crystfel stream parser to return columns for the pixel position of spots. These are called "XDET" and "YDET" following the DIALS (and maybe others?) convention.
=> Modify Crystfel Stream Parser to Return Pixel Coordinates

reciprocalspaceship/concat.py
`rs.concat` does not support generators whereas `pd.concat` does. The reason `rs` does not support them, is that the control flow that checks whether the arguments are isomorphous specifically [indexes the first element in the passed sequence](https://github.com/Hekstra-Lab/reciprocalspaceship/blob/3e66ad04ffeb69eccb277d1afb2ab9c0a4a9defa/reciprocalspaceship/concat.py#L32). This only works for subscriptable objects. Instead, implementing this control flow using `itertools.tee` allows us to bypass the requirement that the passed sequence be subscriptable.
=> add support for generators to rs.concat

reciprocalspaceship/dataset.py, tests/test_dataset.py
I added a method to `rs.DataSet` which just drops systematically absent rows. This saves the user having to do something like
```python
ds = ds[~ds.label_absences().ABSENT]
```
which can now by done by
```python
ds = ds.remove_absences()
```
. This method supports the `inplace` argument, and by using `pd.DataFrame.drop` and operating at the `ds.index` level, I think it avoids using extra memory unnecessarily. This will be helpful for large, unmerged datasets. The recipe was a tad tricky to work out, so I figured we should just put it in a method. (Admittedly this part is a premature optimization, but I do think the method makes code cleaner at the user level). 
@JBGreisman , let me know what you think
=> Added convenience function to remove systematic absences

reciprocalspaceship/utils/cell.py
I had flipped the h,k,l axis limits when generating reciprocal cells which worked okay for low resolution tests with cube-ish cells. So, my test didn't catch it. I'll try to cook up a test later this week, but this is such an obvious bug that I will merge it first. I can probably relax the little oversampling I was doing in the original method as well.
=> use correct hkl resolution limits

reciprocalspaceship/dataset.py, renovate.json
When applying `black` to the codebase (#86), it appears that I reverted `DataSet.compute_dHKL()` to not use the changes made in #87. This PR corrects that reversion. 
After merging in this PR, `DataSet.compute_dHKL()` will use `gemmi` for computing resolution of reflections.
=> Fix reversion in dataset.py (#87)

reciprocalspaceship/dataset.py, reciprocalspaceship/decorators.py, reciprocalspaceship/utils/asu.py, reciprocalspaceship/utils/cell.py, reciprocalspaceship/utils/phases.py, reciprocalspaceship/utils/stats.py, reciprocalspaceship/utils/structurefactors.py, tests/test_decorators.py, tests/utils/test_centrics.py, tests/utils/test_multiplicity.py, tests/utils/test_structurefactors.py
Fixes #92.
It is common in `rs` to write functions that take `gemmi.SpaceGroup` or `gemmi.UnitCell` instances as arguments. In order to make these methods more flexible, it is often useful to add error checking code so that if an `int` is provided instead of a `gemmi.SpaceGroup`, the method generates the equivalent `gemmi` object instance. This was done for the `DataSet.cell` and `DataSet.spacegroup` setter methods to address #18.
This PR generalizes this idea using `@spacegroupify` and `@cellify` decorators to avoid needing to write boiler plate argument checking code. This allows one to write a function as if it is guaranteed that the input argument is a `gemmi` object, while still being able to input that argument flexibly. For example:
```python
from reciprocalspaceship.decorators …
```
=> Add decorators for gemmi argument checking

reciprocalspaceship/utils/asu.py
For some reason we never vectorized `utils.in_asu`. This fixes that and removes some unused variables. EOM.
=> vectorize utils.in_asu

reciprocalspaceship/io/mtz.py, tests/io/test_mtz.py
This PR fixes #110 to ensure that unmerged reflections are not moved to the reciprocal ASU after a call to `DataSet.write_mtz()`.
=> `DataSet.write_mtz()` should not move unmerged reflections to reciprocal ASU

.github/workflows/build.yml, .github/workflows/documentation.yml, .github/workflows/publish.yml, setup.py
Numpy recently removed support for Python 3.7. This PR follows suit, changing the Python requirements to >3.8 and adjusting the CI accordingly.
=> Remove support for Python 3.7

postBuild, setup.py
This PR refactors `setup.py` to remove unnecessary dependencies for running the example notebooks. This will hopefully speed up the binder load time a bit (#123).
=> Add `[examples]` dependencies to simplify installation for binder

reciprocalspaceship/dataset.py, tests/test_dataset_anomalous.py
This was pretty straightforward. Now, if you attempt to call `DataSet.stack_anomalous()` on a dataset containing columns such as `I`, `I(+)`, and `I(-)`, you are greeted with the error message:
```
ValueError: Stacking anomalous data will result in duplicate column names. Rename or drop column 'I' and try again.
```
I also added `test_stack_anomalous_duplicates()` to `test_dataset_anomalous.py` to verify this behavior.
In the previous version of `DataSet.stack_anomalous()`, the line:
```python
new_labels = [l.rstrip(suffixes[0]) for l in plus_labels]
```
comes after the following:
```python
centrics = self.label_centrics()["CENTRIC"]
dataset_plus = self.drop(columns=list(minus_labels))
dataset_minus = self.loc[~centrics].drop(columns=list(plus_labels)) …
```
=> Raise ValueError when stack_anomalous() will result in duplicate column names

reciprocalspaceship/io/precognition.py, tests/io/test_precognition.py
Accomplished all of the changes mentioned in #135 . Two outstanding thoughts:
- Though I did clarify in the docs that `.ii` files are allowed, I didn't want to change the name of the `hklfile` argument for fear of breaking backwards compatibility. That said, I know this function hasn't really seen a lot of daylight, so I'm happy to be overruled there.
- I added a `ValueError` for when a `cell` argument is provided but doesn't have length 6. Previously, the function checked for this length, but then just silently ignored an argument with the wrong length. I didn't add a test for this behavior, thinking that was overkill, but I could add that if desired.
Also, as best I can tell, this is the first "warning" in `reciprocalspaceship`. If some mechanism other than the built-in `warnings` …
=> Fixed `read_precognition()` as per #135 and updated tests

reciprocalspaceship/dtypes/base.py, tests/dtypes/test_dtypes.py, tests/test_dataset.py
This PR addresses #144, allowing integer-backed column types containing NaNs to be converted to float ndarrays.
Importantly, this ensures that phenix output MTZs can be "round-trip" read/written, and converted to/from `gemmi`
=> Allow integer-backed columns with NaNs to be converted to float dtype

docs/userguide/mtzdtypes.ipynb, reciprocalspaceship/dtypes/summarize.py
Fixes #141 -- updates broken URL in documentation and `rs.summarize_mtz_dtypes()` docstring
=> Update documentation links to CCP4 MTZ column-types

reciprocalspaceship/concat.py, reciprocalspaceship/dataset.py, reciprocalspaceship/utils/stats.py, tests/test_dataset_preserve_attributes.py
This PR fixes #146 to remove the overloaded function, `DataSet.append()`, and any uses of it.
=> Remove `DataSet.append()` due to upcoming deprecation in Pandas

reciprocalspaceship/dataset.py, tests/test_dataset.py
This PR adds a new function to `DataSet`, `select_mtzdtype()`:
```python
In [1]: rs.DataSet.select_mtzdtype?
Signature: rs.DataSet.select_mtzdtype(self, dtype)
Docstring:
Return the subset of the DataSet’s columns that are of the given dtype.
Parameters
----------
dtype : str or instance of MTZDtype class
Single-letter MTZ code, name, or MTZDtype class to return
Returns
-------
DataSet
Subset of the DataSet with columns matching the requested dtype. If
no columns of the requested dtype are found, an empty DataSet is
returned.
Raises
------
ValueError
If `dtype` is not a string nor a MTZDtype class
File:      ~/Documents/Hekstra_Lab/github/reciprocalspaceship/reciprocalspaceship/dataset.py
Type:      function
```
This PR fixes #104, making it easier to subset a `DataSet` to columns of a …
=> Add `DataSet.select_mtzdtype()` to subset `DataSet` by MTZ column type

tests/test_dataseries.py
Tiny PR -- this just adjust one of the `DataSeries` tests to stop it from generating a `FutureWarning` related to an upcoming change in Pandas behavior. This is a preemptive change to avoid an issue with a future Pandas version.
=> Fix DataSeries test that generates a FutureWarning

reciprocalspaceship/dataset.py, reciprocalspaceship/io/mtz.py, tests/io/test_mtz.py
This PR addresses #103 by adding an interface for setting the project, crystal, and dataset names in `DataSet.to_gemmi()` and `DataSet.write_mtz()`. These names are then set in the MTZ file or `gemmi.Mtz` object.
This can be useful for record keeping, allowing custom titles in MTZ files that can be read by other programs. 
These names default to "reciprocalspaceship" -- if these new arguments are left unset, a user will have the same behavior as before.
=> Add interface for setting project, crystal, and dataset names

reciprocalspaceship/utils/structurefactors.py
This PR rewrites `rs.utils.compute_structurefactor_multiplicity()` to be implemented with methods provided by the `gemmi.GroupOps` class. Originally, we had implemented this on our own to vectorize the calculation; however, a vectorized version of this calculation is now provided in `gemmi`.
=> Use gemmi method to implement `rs.utils.compute_structurefactor_multiplicity()`

docs/api/index.rst, reciprocalspaceship/algorithms/__init__.py, reciprocalspaceship/algorithms/intensity.py, tests/algorithms/test_intensity.py
Now with the desired `DataSet`-based API.
I ended up deciding to name the new columns `I_back` and `SigI_back` by default, and to raise a `ValueError` if the method would overwrite a column. Happy to be overruled on one or both of those.
=> Add function to convert structure factor amplitudes to intensities to `algorithms` submodule

reciprocalspaceship/utils/rfree.py, tests/utils/test_rfree.py
1. Support ccp4 convention now: 0 is the test set and key is FreeR_flag
2. Update related test codes
3. Fix the previous bugs about updating more than the free flag column. Add some test codes to prevent such issues in the future.
=> Add features to the add_rfree function

reciprocalspaceship/utils/rfree.py, tests/utils/test_rfree.py
Making changes to `rs.utils.add_rfree` as per #169 and changes to `rs.utils.copy_rfree` as per #159 
The `seed` is passed through to `np.random.default_rng(seed)`, such that running `add_rfree` again with the same `seed` results in the same flags. `seed` defaults to `None`, and conveniently `np.random.default_rng(None)` is a valid call.
A test was added to `test_add_rfree()` to confirm that flags are the same when a seed is used, and are different when a seed is not used.
The recent addition of the `ccp4_convention` parameter to `add_rfree` means that there are two possible names for an r-free column, `"R-free-flags"` (phenix convention) or `"FreeR_flag"` (ccp4 convention). `copy_rfree` will now by default search the provided `dataset_with_rfree` for a column named `"R-free-flags"`, then …
=> Updated functionality for `add_rfree` and `copy_rfree`

reciprocalspaceship/utils/symop.py, tests/conftest.py, tests/utils/test_symop.py
This PR fixes #134 by adding some additional logic to `rs.utils.apply_to_hkl()`. Before, the use of `np.floor_divide()` would return the closest integer HKL, regardless of whether the true symmetry operation yielded a fractional result. Now, symmetry operations that produce non-integer output on the given Miller indices raise a `RuntimeError`
=> Handle symmetry ops that produce fractional HKLs in `apply_to_hkl()`

reciprocalspaceship/utils/__init__.py, reciprocalspaceship/utils/asu.py, reciprocalspaceship/utils/phases.py, reciprocalspaceship/utils/symmetry.py, tests/data/gen_sgtbx_is_polar.py, tests/data/sgtbx/sgtbx_polar.csv, tests/utils/test_polar.py
Aligning maps of isomorphous structures can benefit from classifying polar space groups. This is useful for distinguishing which cases have a discrete set of alternative origins vs. continuous alternatives (see #174).
This PR implements a `reciprocalspaceship.utils.is_polar()` utility function that classifies a space group as polar. This function is tested against the 530 spacegroup settings in `sgtbx`.
=> Add `is_polar()` utility for classifying polar space groups

reciprocalspaceship/utils/__init__.py, reciprocalspaceship/utils/symmetry.py, tests/data/gen_sgtbx_is_polar.py, tests/data/sgtbx/sgtbx_polar.csv, tests/utils/test_polar.py
Based on the routine implemented in `is_polar()`, it's also possible to return which of the cell axes in a given spacegroup are polar (permit continuous origin shifts). This is implemented here as `rs.utils.polar_axes()` with the following call signature:
`polar_axes(spacegroup) --> List(3) of bools`
For example:
```python 
import reciprocalspaceship as rs
print(rs.utils.polar_axes("P 1"))         # [True, True, True]
print(rs.utils.polar_axes("P 1 21 1"))    # [False, True, False]
print(rs.utils.polar_axes("P 21 21 21"))  # [False, False, False]
```
One implementation decision was to only support hexagonal Bravais lattices for the relevant "R 3" trigonal space groups. This decision is made so that it is clear that the function returns polar axes corresponding to the a, b, and c-axes, and …
=> Add `rs.utils.polar_axes()` for classifying which cell axes permit continuous origin shifts

reciprocalspaceship/utils/__init__.py
I forgot to add `rs.utils.is_polar()` and `rs.utils.polar_axes()` to `rs.utils.__all__`, which means that the functions were left off the "Developers" section of the documentation. This PR adds those functions to `rs.utils.__all__` so that the functions are added to the utility functions documentation (https://hekstra-lab.github.io/reciprocalspaceship/developers/utilities.html)
=> Add `is_polar()` and `polar_axes()` to utility functions docs

reciprocalspaceship/dataset.py, tests/dtypes/test_dataset_to_numpy.py
Pandas DataFrames that contain ExtensionDtypes always default to output data with `object` dtype when `DataFrame.to_numpy()` is called. This is suboptimal for MTZ data, which by construction must be compatible with `float32`, and possibly `int32`. 
This PR wraps the pandas call with `DataSet.to_numpy()` to assess whether a more sensible default (either `float32` or `int32`) can be used based on the existing data. This should help to avoid cases where data is unnecessarily cast to an `object` array, which can lead to unexpected behavior downstream.
=> `DataSet.to_numpy()` should use numpy dtypes whenever possible

reciprocalspaceship/dataset.py, tests/test_dataset_symops.py
As discussed in #173, it is useful to have ways to get merohedral twin laws, which are possible reindexing operations for resolving ambiguities. In other analysis tasks, it might be useful to get the full set of possible pseudo-merohedral twin laws for a `DataSet` with its spacegroup/cell.
This PR adds an attribute (`DataSet.reindexing_ops`) to access merohedral twin laws and a method (`DataSet.find_twin_laws()`) which can be used to access the full list of possible twin laws. These are implemented using calls to `gemmi.find_twin_laws()` and are tested against `gemmi` and expected properties of the functions/twin laws.
=> Add `DataSet.reindexing_ops` and `DataSet.find_twin_laws()`

reciprocalspaceship/dataset.py, reciprocalspaceship/stats/completeness.py, reciprocalspaceship/utils/binning.py, tests/test_dataset.py, tests/test_dataset_binning.py, tests/utils/test_binning.py
Fixes #184 by adding a `return_edges` argument to `DataSet.assign_resolution_bins()`. This PR adds that flexibility to the API, but otherwise does not change the default behavior of the function to preserve backwards compatibility.
=> Add return_edges argument to DataSet.assign_resolution_bins()

README.md
The badge for the MIT license in our README.md appears to be broken -- this replaces the badge icon to something that appears to work.
=> Update broken MIT license badge in README.md

.pre-commit-config.yaml, setup.py
This is a quick fix to the documentation build. There is a current issue with sphinx due to a newer version of Jinja2 (https://github.com/readthedocs/readthedocs.org/issues/9037#issuecomment-1077818554).
After this fix, I'll look into making a more future-proof documentation build -- might require updating to using a more recent Python version when building documentation.
=> Fix documentation build by lowering jinja2 version

.github/workflows/testdocumentation.yml
This PR adds a GitHub Action workflow that builds the static documentation site using sphinx. This addresses a lingering issue that the documentation build is only attempted upon merging into the `main` branch. This way we can catch issues before merging. 
This workflow is equivalent to the documentation build, but any changes are not added to the `gh-pages` branch and the site itself is not updated.
=> Add GitHub Action for testing documentation build during pull requests

docs/conf.py, docs/index.rst, setup.py
The documentation used a deprecated sphinx extension called `sphinx_panels`. This update switches to the updated version called `sphinx_design`. This should make it so that a later version of sphinx can be used for building documentation, which resolves the jinja2 version issue from #202 and as a side effect also resolves the issue identified in #206.
This worked locally without the need for setting an explicit minimal sphinx version in `setup.py`, but it might behave differently in the CI.
=> Upgrade sphinx version by removing sphinx_panels dependency

reciprocalspaceship/utils/asu.py
This PR addresses #194 to clarify that `rs.utils.in_asu()` does not accept +/- Friedel pairs -- only Miller indices in the +ASU will be labeled as True.
=> Fixes #194: Update rs.utils.in_asu() docstring to clarify behavior

.github/workflows/build.yml
Python 3.11 should be added to the build tests to stay on top of any issues that may arise.
=> Add python 3.11 to build tests

reciprocalspaceship/algorithms/scale_merged_intensities.py
I added a flag permitting clipping of Iobs to positive values for the purpose of calculating Sigma during anisotropic FW calculation. The option is off by default.
=> Support clipping Sigma to avoid negative values in French-Wilson method

reciprocalspaceship/utils/stats.py
This PR just optimizes `rs.utils.weighted_pearsonr` by replacing sequential multiplication and summation with `np.einsum`. This allows numpy to calculate r faster and with less memory.
=> Use einsum in weighted_pearsonr

reciprocalspaceship/decorators.py
This PR modifies the `@spacegroupify` and `@cellify` decorators so as to support decorating functions which take arbitrary keyword arguments (`**kwargs`). Specifically, it alters the usage of the `BoundArguments` instance in the decorated function call. 
`f(**bargs.arguments)` becomes `f(*bargs.args, **bargs.kwargs)`
=> support **kwargs in gemmification decoratored fn

reciprocalspaceship/dataset.py, reciprocalspaceship/dtypes/floating.py, reciprocalspaceship/dtypes/integer.py, reciprocalspaceship/utils/cell.py, reciprocalspaceship/utils/stats.py, reciprocalspaceship/utils/structurefactors.py, tests/algorithms/conftest.py
This PR enables `rs` to run on `numpy` version 2.0 which is also supported by the latest `pandas` release. The major changes required were
- Squeeze extra dim from inverse returned by `np.unique`
- `np.find_common_type` was removed in version 2.0, but pandas provides an equivalent method, `from pandas.core.dtypes.cast import np_find_common_type`
- Remove `np.NaN` which is now exclusively `np.nan`
- `np.array` no longer supports `np.array(list, copy=False`. So I added some control flow which relies on `np.asarray`.
=> enable numpy 2.0 support

reciprocalspaceship/dtypes/floating.py, reciprocalspaceship/dtypes/integer.py, reciprocalspaceship/dtypes/internals.py
This PR speeds up dataset creation for large arrays. In working on a new stream file parser, I realized that converting numpy float32 and int32  to MTZDtypes  could be very time-consuming for large arrays. After some digging, I found out the culprit was a cython function provided by pandas, `pandas._libs.missing.is_numeric_na` which makes a mask for missing values in `rs` 
- ['floating.py`](https://github.com/rs-station/reciprocalspaceship/blob/2ef8ae44b3d3d456cf6ba2efdcd751c65c04330c/reciprocalspaceship/dtypes/floating.py#L163)
- ['integer.py'](https://github.com/rs-station/reciprocalspaceship/blob/2ef8ae44b3d3d456cf6ba2efdcd751c65c04330c/reciprocalspaceship/dtypes/integer.py#L205)
In the case that the input is an int32 or float32 numpy array, this is wholly unnecessary, and it is much …
=> Is numeric na

reciprocalspaceship/dataset.py, reciprocalspaceship/decorators.py, reciprocalspaceship/io/mtz.py, tests/io/test_mtz.py
PR fixes #255. 
Currently, DataSet objects with a pd.RangeIndex() (for example, due to a call to `DataSet.reset_index()`) end up causing trouble due to an extra call to `reset_index()` within `rs.io.mtz.to_gemmi()`. To resolve this issue, this PR uses the `range_indexed` decorator to ensure that the relevant functions can assume the calling `DataSet` object is always range indexed. This simplifies the control flow for these functions.
As part of this PR, I also modified `range_indexed` to handle use cases where the decorated function returns None or non-DataSet types.
=> Add support for range indexed data in `DataSet.write_mtz()` and `DataSet.to_gemmi()`

reciprocalspaceship/dataset.py, tests/test_dataset_signatures.py
There was an update to the pandas API in v1.5 that changed the `pd.DataFrame.reset_index()` call signature. This PR updates the call signature of `rs.DataSet.reset_index()` and adds tests to confirm the consistency of the call signature between:
- `rs.DataSet.reset_index()` and `pd.DataFrame.reset_index()`
- `rs.DataSet.set_index()` and `pd.DataFrame.set_index()`
=> Update `rs.DataSet.reset_index()` call signature to matches `pandas >v1.5`

reciprocalspaceship/io/crystfel.py
This is a small addition to the `rs.read_crystfel()` docstrings to include descriptions of the returned columns. The descriptions are rendered as a list on the updated documentation page:
=> Add description of columns returned by `rs.read_crystfel()`

reciprocalspaceship/dataset.py, tests/test_dataset.py
As discussed in #277 , DataSet.is_isomorphous currently does not do what is indicated in its docstring. This change makes the behavior in line with the expectation that `cell_threshold` is a percent difference.
=> Fix is_isomorphous

docs/api/cifdump.rst, docs/api/index.rst, reciprocalspaceship/commandline/cifdump.py, setup.py
Given the recent change by the PDB to no longer provide MTZ files for structures (https://www.rcsb.org/news/feature/66ead31f2c751d5c77fbb706) it would be very useful to have a CLI tool equivalent to `mtzdump` for CIF files. We plan on using this repo at my workplace and this feature would be of great utility to us.
This was brought up in #229 and the changes are relatively straightforward given that `rs` can already read CIF files. Most of the logic was taken from the existing `mtzdump` utility.
- `cifdump` can be accessed from the CLI
- `cifdump` can be used to log the contents of a structure factor CIF file from the PDB
- Docs can be built and new CLI utility appears
=> Add cifdump CLI utility

reciprocalspaceship/dataset.py
This is a very minor bookkeeping PR -- we currently have two function for converting a `DataSet` to a 3D numpy array representing the underlying data: `DataSet.to_reciprocalgrid()` and `DataSet.to_reciprocal_grid()`. The former will be deprecated in favor of the latter, in order to have consistency naming schemes in terms of underscores.
However, we currently have duplicate implementations for both functions. If we want to edit the implementations before we officially remove one of them, we will need to make changes in both places. This PR updates the deprecated code to call the newer version to avoid needing to maintain the code in two places.
=> Deprecated `DataSet.to_reciprocalgrid()` should call `DataSet.to_reciprocal_grid()`

reciprocalspaceship/dataset.py, reciprocalspaceship/io/precognition.py, tests/conftest.py, tests/test_dataset.py
This PR makes a `.hkls` attribute for `rs.DataSet` instances. The method has a setter to assign new Miller indices. It retains backward compatibility with the `get_hkls` method. 
The use case here is for being able to set new miller indices using an expression like
```python
ds.hkls = hkls
```
where hkls can either be a dataset containing the keys 'H', 'K', and 'L' or it could be a numpy array. This saves the user having to reset and set the index.
=> add hkls attribute rs.DataSet

reciprocalspaceship/dtypes/internals.py, tests/dtypes/test_floats_pandas.py, tests/dtypes/test_ints_pandas.py
This PR makes small changes to the CI and storage of `NaN` values in our ExtensionDtypes to address deprecation warnings. 
There are still two remaining sets of warnings, but these are in tests that are directly inherited from pandas. As such, I'll let these be fixed in the pandas codebase itself, rather than overloading and correcting them:
```
===================================================== warnings summary =====================================================
tests/dtypes/test_floats_pandas.py: 13 warnings
tests/dtypes/test_ints_pandas.py: 4 warnings
site-packages/pandas/tests/extension/base/setitem.py:227: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame …
```
=> Address Pandas warnings raised in CI
